blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas / Feature Request
    url: https://github.com/code4moldova/catalog-profesii/discussions/categories/ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: 🙏 Help
    url: https://github.com/code4moldova/catalog-profesii/discussions/categories/help
    about: If you have a question or need help, ask a question on the discussion forums.
  - name: 💬 Slack Discussions
    url: https://code4md.slack.com/
    about: Please ask and answer questions here.
